services:
    postgres:
        image: postgres:10.5
        # could randomize this, but no need except for crashes
        container_name: postgres
        volumes:
          - './pg_init:/docker-entrypoint-initdb.d/'
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - APP_DB_USER=${APP_DB_USER}
          - APP_DB_PASS=${APP_DB_PASS}
          - APP_DB_NAME=${APP_DB_NAME}
        networks:
          - backend

networks:
  backend: